# Generated by Django 5.1.6 on 2025-03-02 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_invoiceitem_invoice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='date',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='net_payable_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='remarks',
        ),
    ]
