# Generated by Django 5.1.6 on 2025-03-02 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_invoice_discount_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='net_payable',
        ),
    ]
