# Generated by Django 5.1.6 on 2025-03-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_remove_invoice_net_payable'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payable_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
