# Generated by Django 5.1.6 on 2025-03-02 18:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_expense_payment_mode_alter_expense_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(default=0.0, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='billing.inventoryitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer_mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
