# Generated by Django 5.1.6 on 2025-03-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_regitration'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_id',
            field=models.CharField(default=None, editable=False, max_length=20, unique=True),
        ),
    ]
