# Generated by Django 5.1.6 on 2025-03-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_invoice_invoice_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='discount_percentage',
        ),
    ]
