# Generated by Django 5.1.6 on 2025-03-06 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0026_salereturn_delete_salesreturn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salereturn',
            old_name='quantity',
            new_name='return_quantity',
        ),
    ]
