# Generated by Django 5.1.6 on 2025-03-06 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_rename_quantity_salereturn_return_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereturn',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
