# Generated by Django 5.1.6 on 2025-03-06 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_alter_salereturn_refund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salereturn',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='salereturn',
            name='return_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
