# Generated by Django 5.1.6 on 2025-03-06 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0030_salesreturn_salesreturnitem_delete_salereturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Business', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
    ]
