# Generated by Django 5.1.6 on 2025-03-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0031_businessinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='address',
            field=models.TextField(default='Not Provided'),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='contact',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='gst_no',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AddField(
            model_name='businessinfo',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
