# Generated by Django 5.1.6 on 2025-03-07 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0033_invoice_gst_invoice_price_invoice_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesreturnitem',
            name='invoice_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice'),
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
