# Generated by Django 5.1.6 on 2025-03-07 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_invoiceitem_alter_salesreturnitem_invoice_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='gst',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='product',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='quantity',
        ),
    ]
