# Generated by Django 5.1.6 on 2025-03-07 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_invoice_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreturnitem',
            name='sales_return',
        ),
        migrations.RemoveField(
            model_name='salesreturnitem',
            name='invoice_item',
        ),
        migrations.CreateModel(
            name='ProductReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_returned', models.IntegerField()),
                ('return_reason', models.TextField(blank=True, null=True)),
                ('return_date', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_returns', to='billing.invoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.inventoryitem')),
            ],
        ),
        migrations.DeleteModel(
            name='SalesReturn',
        ),
        migrations.DeleteModel(
            name='SalesReturnItem',
        ),
    ]
