# Generated by Django 5.1.6 on 2025-03-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_remove_salesreturnitem_sales_return_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productreturn',
            old_name='quantity_returned',
            new_name='quantity',
        ),
    ]
