# Generated by Django 5.1.6 on 2025-03-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0043_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Regitration',
        ),
    ]
