# Generated by Django 5.1.6 on 2025-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0044_delete_regitration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='username',
            field=models.CharField(default='temp_user', max_length=150, unique=True),
        ),
    ]
