# Generated by Django 5.1.6 on 2025-03-08 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0047_supplier_user_alter_inventoryitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.registration'),
            preserve_default=False,
        ),
    ]
