# Generated by Django 5.1.6 on 2025-03-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0049_productreturn_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productreturn',
            name='user',
        ),
    ]
