# Generated by Django 5.1.6 on 2025-03-08 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0051_productreturn_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.registration'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='billing.registration'),
            preserve_default=False,
        ),
    ]
