# Generated by Django 5.1.6 on 2025-03-08 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0055_regitration_remove_expense_user_remove_invoice_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessInfo',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Expense',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productreturn',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Regitration',
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='ProductReturn',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceItem',
        ),
    ]
