# Generated by Django 5.1.6 on 2025-03-09 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0058_registration_delete_regitration'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regitration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
