# Generated by Django 5.1.6 on 2025-03-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0059_regitration_delete_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
